### ISSUE TITLE
[Feature reqeust] Save / Load diagram

### ISSUE THREAD

**Issue by BenKyos** [TablePlus/diagram-plugin#1]
Next to the export diagram feature, it would be nice to have an option to save and load the diagram to be able to edit it at a later time or to share it with someone else who can also edit it.

**Comment by dvkndn** [comment]
Thank @BenKyos we're already working on it :smile:

**Comment by dvkndn** [comment]
Hi sorry I forgot to update with you. All are possible now on both the web version and the plugin for TablePlus Mac and Windows app. You can export/save your diagrams to a file or to your clipboard, and your friends can import it in their plugin or browser.

There's also a Library so you can manage all of your diagrams :D

**Comment by BenKyos** [comment]
Love it!
