### ISSUE TITLE
Relationship arrows displayed incorrectly after arrange in zoom in or zoom out mode

### ISSUE THREAD

**Issue by smonv** [TablePlus/diagram-plugin#10]
Zoom in:

<img width="1238" alt="Screen Shot 2020-10-23 at 10 26 34" src="https://user-images.githubusercontent.com/8962973/96953101-846cfc00-151a-11eb-8b99-1e022376050b.png">
<img width="1241" alt="Screen Shot 2020-10-23 at 10 26 43" src="https://user-images.githubusercontent.com/8962973/96953113-88991980-151a-11eb-87d9-603cff495522.png">

Zoom out:
<img width="1343" alt="Screen Shot 2020-10-23 at 10 26 55" src="https://user-images.githubusercontent.com/8962973/96953124-8f279100-151a-11eb-996f-3034180c9efd.png">

TablePlus: build 348
macOS: 11 BigSur beta 10
Diagram Generator: v3.7

**Comment by dvkndn** [comment]
ah yes :( sorry about that. The "auto arrange" feature currently doesn't work properly with zoom. We will fix it soon

**Comment by dvkndn** [comment]
Btw for testing purpose, have you able to zoom via `CMD -` and `CMD +`?

**Comment by smonv** [comment]
> Btw for testing purpose, have you able to zoom via `CMD -` and `CMD +`?

Just tried, zoom function working correctly via `CMD -` and `CMD +`.

**Comment by dvkndn** [comment]
@smonv thank you! Just want to make sure that it only zoom the canvas, not the whole app :D

**Comment by dvkndn** [comment]
Actually the "drag to select" also doesn't work properly when zooming. I'll fix both

**Comment by dvkndn** [comment]
Both are fixed! Will be included in the upcoming release

**Comment by smonv** [comment]
Thank you. Hope all the fixes will be release soon.

**Comment by dvkndn** [comment]
We've just released a new version :D Please update the diagram plugin via Plugin Manager (Cmd + L or Ctrl + L)

**Comment by smonv** [comment]
> We've just released a new version :D Please update the diagram plugin via Plugin Manager (Cmd + L or Ctrl + L)

Thank you for the release, can confirm bug fixed.
