### ISSUE TITLE
[feature request] change column order by hold and dragging data row

### ISSUE THREAD

**Issue by smonv** [TablePlus/diagram-plugin#13]
Currently, whenever I click on a row in one table diagram, the table enters edit mode. Besides that, I could not find a way to re-arrange or change the order of each row. I think the ability to change row order by dragging the row will be crucial when updating a table.

**Comment by dvkndn** [comment]
Yes that's already on our TODO!

**Comment by smonv** [comment]
@dvkndn One more question. Is TablePlus have any way to access diagram window directly? Currently, I can only access menu 'Plugins > Empty Diagram' after open a database, and after diagram window open, I have to delete the empty diagram.

**Comment by dvkndn** [comment]
@smonv hm currently not, but I think we will have a button for that :D

**Comment by dvkndn** [comment]
Just a small update that this is implemented and will be available in the upcoming release :D I'll update here one more time on the release

**Comment by smonv** [comment]
> Just a small update that this is implemented and will be available in the upcoming release :D I'll update here one more time on the release

Happy to see this coming. Thank you for your dedicated support.

**Comment by dvkndn** [comment]
Hi can you check again on https://diagramplus.com or update the plugin (Cmd/Ctrl + L)? The feature has been released :D

**Comment by smonv** [comment]
> Hi can you check again on https://diagramplus.com or update the plugin (Cmd/Ctrl + L)? The feature has been released :D

Thank for the release. I just test new feature and it's working flawlessly.
