### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by nezaboravi** [TablePlus/diagram-plugin#17]
All i can see is to open an empty diagram?
How to create a diagram from existing table? Some screenshots would be helpful.

**Comment by huyphams** [comment]
Hi @nezaboravi please check this.
<img width="687" alt="Screen Shot 2020-11-08 at 6 18 23 PM" src="https://user-images.githubusercontent.com/3654622/98463584-ccfd0880-21ee-11eb-9a0c-cad30efa71a1.png">

**Comment by dillingham** [comment]
@huyphams  that would be helpful on the readme
