### ISSUE TITLE
Foreign key association on exporting diagram as SQL

### ISSUE THREAD

**Issue by gohirosh** [TablePlus/diagram-plugin#25]
Hi there. I am trying exporting as MySQL sentences and it seems foreign key is added on the opposite direction. For example in airline sample,  it generates "ALTER TABLE `new`.`Airports` ADD FOREIGN KEY (`airport_code`) REFERENCES `new`.`Flights` (`arrival_airport`);"). I fixed the column name for understanding. thanks in advance.

**Comment by SDeans0** [comment]
This bug still exists as of Feb 2022.
