### ISSUE TITLE
Does this work outside of TablePlus?

### ISSUE THREAD

**Issue by lordlycastle** [TablePlus/diagram-plugin#3]
Can this library/package be used without TablePlus to generate diagrams (SVG) for DBs? Would love to use it for some automated diagram generation.

**Comment by dvkndn** [comment]
At the moment using the Diagram plugin as a library is not a use case we can officially supported. The code here is a bundled JS that is built for TablePlus only.

We do support using it on its own like a web app at https://diagramplus.com (but the web app version cannot connect to databases).

Technically it's possible to use the JS here on your own, or use a headless browser to automate using the web app, but in conclusion we don't support that.

**Comment by lordlycastle** [comment]
Thanks for the info @dvkndn!
