### ISSUE TITLE
Error submitting issue from within the app

### ISSUE THREAD

**Issue by formido** [TablePlus/diagram-plugin#4]
When I tried to report TablePlus/TablePlus#2136, I got this error.

![image](https://user-images.githubusercontent.com/22295/96476673-633e9f80-11ea-11eb-9d6d-16da9e7a1344.png)

Happened multiple times so I went to the repo with it

**Comment by dvkndn** [comment]
Sorry about this :( We are on it!

**Comment by dvkndn** [comment]
Sorry for the late update. This was fixed in the upcoming release :D

**Comment by formido** [comment]
Not at all, you work fast. Great app, too!

**Comment by dvkndn** [comment]
I think this issue can be closed. The new version is released long ago (sorry I did not update here) and you can rest assure that all reports go straight to our slack!

**Comment by formido** [comment]
Oh, did you want me to close it?
