### ISSUE TITLE
Incorrect relationship arrow when export diagram to PNG image

### ISSUE THREAD

**Issue by smonv** [TablePlus/diagram-plugin#9]
Thank you for your wonderful application.

I played with diagram-plugin and tried to generate the image but noticed some weird black region and no arrow on the exported image. This happens with both high-quality and low-quality options.

High quality:
![diagram high](https://user-images.githubusercontent.com/8962973/96950403-6ac8b600-1514-11eb-8ecf-75b98f377599.png)

Low quality:
![diagram low](https://user-images.githubusercontent.com/8962973/96950411-70260080-1514-11eb-8472-821b6cd1add0.png)
 

TablePlus: build 348
macOS: 11 BigSur beta 10
Diagram Generator: version 3.7

**Comment by dvkndn** [comment]
Oh sorry. This is weird I thought I fixed it but it seems to come back haunting me.. I'll check it right now

**Comment by dvkndn** [comment]
Fixed! Will be in the upcoming release

**Comment by smonv** [comment]
wow, that was fast.

Thank for the fix.

**Comment by dvkndn** [comment]
We've just released a new version :D Please update the diagram plugin via Plugin Manager (Cmd + L or Ctrl + L)

**Comment by smonv** [comment]
Just update, confirm bug fixed.

One more thing, can you make the export function only generate image large enough to cover all the tables? Currently, I only have 3 tables, but the image generated include a large background area for nothing, make the actual area of the table diagram so small.

![diagram](https://user-images.githubusercontent.com/8962973/96959342-ff89de80-1529-11eb-8fe2-3530f37dc8c6.png)

**Comment by dvkndn** [comment]
Sure let me fix that too
